---
title: "Yelp API"
author: "Anna Duan"
date: "`r Sys.Date()`"
output: html_document
---
# Setup
## Libraries
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# libraries 
library(tigris)
library(yelpr)
library(tidyverse)
library(sf)
library(mapview)
library(httr)
library(viridis)
```

## Tigris boundaries 
```{r load tigris boundaries}
options(tigris_use_cache = TRUE) # set cache = TRUE to save time for future calls

zcta <- zctas(year = 2021) %>% # get all ZIPs in US (we can't filter by state unfortunately)
  rename(zip_code = GEOID20) %>% 
  st_transform("EPSG:2272") %>% # re-project
  filter(substr(ZCTA5CE20, start = 1, stop = 3) == "191") %>%
  erase_water(area_threshold = 0.5)

zcta_bg <- zctas(year = 2021) %>% # get all ZIPs in US
  rename(zip_code = GEOID20) %>% 
  st_transform("EPSG:2272") %>% # re-project
  st_crop(st_bbox(zcta %>% st_buffer(5000))) %>%
  erase_water(area_threshold = 0.5)


zip_list <- zcta$ZCTA5CE20 # list of zip codes to include in API query

phl_bound <- st_union(zcta) %>% # phl boundary
  st_as_sf()

roads_pa <- primary_secondary_roads(state = "PA", year = 2021) %>%
  st_transform("EPSG:2272") %>%
  st_crop(st_bbox(zcta %>% st_buffer(5000))) %>%
  erase_water()

roads_nj <- primary_secondary_roads(state = "NJ", year = 2021) %>%
  st_transform("EPSG:2272") %>%
  st_crop(st_bbox(zcta %>% st_buffer(5000))) %>%
  erase_water()

roads <- rbind(roads_nj, roads_pa)

```
# Yelp Fusion API
## get_yelp() function
```{r get yelp function}
#### Yelp api call function ####
url <- "https://api.yelp.com/v3/businesses/search"

get_yelp = function(category, zip_code, offset_num) { # args are category of business, zipcode, and number to offset by
  
  queryString = list(
    location = zip_code, # argument to be filled
    term = category, # argument to be filled
    sort_by = "distance", # sort by dist
    limit = 50, # 50 is the max for yelp fusion api, any higher and it won't work
    offset = offset_num # argument to be filled
  )
  
  # use "GET" verb to request information from url
  response <- VERB("GET", url, query = queryString, 
                   add_headers('Authorization' = 'Bearer yKhYlEbDS83IT8QAX9xmAnTSecHwHlsMnqS1-JXEnPG9LoNNwn2BxqMYd4DaJKw-zS-WAw8lPPGW943nrGPp6NynuQuQmyzKLDcH0q42lwVfTMGxb3csS2u6hCMgZXYx'), 
                   content_type("application/octet-stream"), 
                   accept("application/json"))
  
  # turn the response into a json file
  yelp.json = content(response, "parsed", flatten = TRUE, simplify = TRUE)
  
  # retrieve columns from json structure
  biz.id = data.frame(yelp.json$businesses$id)
  biz.name = data.frame(yelp.json$businesses$name)
  biz.lat = data.frame(yelp.json$businesses$coordinates.latitude)
  biz.lon = data.frame(yelp.json$businesses$coordinates.longitude)
  biz.rating = data.frame(yelp.json$businesses$rating)
  biz.addr = data.frame(yelp.json$businesses$location.address1)
  
  # bind the columns into one dataframe
  yelp.df = cbind(biz.id, biz.name, biz.rating, biz.addr, biz.lat, biz.lon)  %>%
    as.data.frame()
  
  colnames(yelp.df) <- c("id", "name", "rating", "address", "lat", "lon")
  
  # add in category alias/title (this will give us cuisine information)
  cuisine = yelp.json$businesses$categories
  
  cuis.df <- map_dfr(cuisine, function(x) {
    tibble(
      alias = paste(x$alias, collapse = ", "),
      title = paste(x$title, collapse = ", ")) %>%
      as.data.frame()
  })
  
  yelp.df <- yelp.df %>%
    cbind(cuis.df)
  
  # # Replace NA values with ""
  # yelp.df <- yelp.df %>% 
  #   mutate(across(everything(), ~replace_na(.x, "")))
  
  # When creating an empty dataframe, use "" as default value
  if(nrow(yelp.df) == 0) {
    yelp.df <- data.frame(name="", rating=numeric(0), address="", lat=numeric(0), lon=numeric(0), alias = "", title = "", stringsAsFactors=FALSE)
  }
  
  return(yelp.df)
}
```

## API call / data collection
```{r call api}
# Initialize a named list of empty dataframes
initialize_named_dfs <- function(zips) { 
  empty_df <- data.frame(name=character(0), rating=numeric(0),  address=character(0), lat=numeric(0), lon=numeric(0))
  named_list <- lapply(zips, function(zip) empty_df)
  names(named_list) <- zips
  return(named_list)
}

biz_list_0 <- initialize_named_dfs(zip_list) # Initiate list of restaurant dataframes for each offset (since the query limit is 50, offset = 1 would return 51-100)
biz_list_1 <- initialize_named_dfs(zip_list) # 10 dfs x 50 restaurants each = a 500 restaurant sample per zip code
biz_list_2 <- initialize_named_dfs(zip_list)
biz_list_3 <- initialize_named_dfs(zip_list)

biz_list_4 <- initialize_named_dfs(zip_list)
biz_list_5 <- initialize_named_dfs(zip_list)
biz_list_6 <- initialize_named_dfs(zip_list)


# master list to store the dataframes
offset_list <- list(biz_list_0, biz_list_1, biz_list_2, biz_list_3,
                    biz_list_4, biz_list_5, biz_list_6)

# Loop through each offset (think of each offset as a page of results)
for (i in 1:length(zip_list)) {
  
  # initialize zipnum (this is so we know where we're at in the list of zips)
  zipnum <- 1
  # initialize offset (so we can pull page 1, then page 2, then page 3, etc)
  offset <- i-1
  
  # Loop through each zip code
  for (zip_code in zip_list) {
    print(paste("batch ", offset + 1, ", ", "zip", zipnum, ": ", zip_code, sep = ""))
    
    # Fetch Yelp data for the zip code and store it in the list
    offset_list[[i]][[as.character(zip_code)]] <- get_yelp("parks", as.character(zip_code), offset)
    
    zipnum <- zipnum + 1 #iterate zipnum each loop
  }
  offset <- offset + 50
}
```

# Data preparation
## Store response as dataframe
```{r gather data to df}
# Combine all dataframes into one dataframe and remove duplicates
biz.sf <- map_dfr(offset_list, ~ bind_rows(.x)) %>%
  unique() %>%
  filter(!is.na(lat)) %>%
  st_as_sf(crs = 4326, coords = c("lon", "lat")) %>% 
  st_transform("EPSG:2272")

park_id <- biz.sf$id
```

```{r parks}

url <- "https://api.yelp.com/v3/businesses/LklDTDwgJLbUjd67ZKsvCg/reviews"

queryString <- list(
  limit = "50",
  sort_by = "newest"
)

response <- VERB("GET", url, query = queryString, add_headers('Authorization' = 'Bearer RF7JfYA8GMJRVlASJCtsrJvLMhE8nbKDjkQ8B_7ZYUPWforzJV1mNDb6ibRWJfMUu_RHFG-NxCF1QHeasyOxlpid7ZbQ1tQBcACDZBWE2rLYKDhWD8Kxps0SZJJCZXYx'), content_type("application/octet-stream"), accept("application/json"))

# turn the response into a json file
  yelp.json = content(response, "parsed", flatten = TRUE, simplify = TRUE)
  
  # retrieve columns from json structure
  review.time = data.frame(yelp.json$reviews$time_created)
  review.rating = data.frame(yelp.json$reviews$rating)
  review.text = data.frame(yelp.json$reviews$text)
  
  # bind the columns into one dataframe
  yelp.df = cbind(review.time, review.rating, review.text)  %>%
    as.data.frame()
  
  colnames(yelp.df) <- c("time", "rating", "text")
  
```

```{r parks function}
get_yelp_reviews <- function(business_id, auth_token) {
  url <- paste0("https://api.yelp.com/v3/businesses/", business_id, "/reviews")

  queryString <- list(
    limit = "50",
    sort_by = "newest"
  )

  response <- httr::VERB("GET", url, query = queryString, add_headers('Authorization' = paste0('Bearer ', auth_token)), content_type("application/octet-stream"), accept("application/json"))

  # turn the response into a json file
  yelp.json <- httr::content(response, "parsed", flatten = TRUE, simplify = TRUE)

  # retrieve columns from json structure
  review.time <- data.frame(yelp.json$reviews$time_created)
  review.rating <- data.frame(yelp.json$reviews$rating)
  review.text <- data.frame(yelp.json$reviews$text)

  # bind the columns into one dataframe
  yelp.df <- dplyr::bind_cols(review.time, review.rating, review.text) %>%
    dplyr::as_tibble()

  # Add a column for the business ID
  yelp.df$business_id <- business_id

  return(yelp.df)
}

# Example usage
auth_token <- "RF7JfYA8GMJRVlASJCtsrJvLMhE8nbKDjkQ8B_7ZYUPWforzJV1mNDb6ibRWJfMUu_RHFG-NxCF1QHeasyOxlpid7ZbQ1tQBcACDZBWE2rLYKDhWD8Kxps0SZJJCZXYx"
all_reviews <- do.call(rbind, lapply(park_id, function(id) get_yelp_reviews(id, auth_token)))

reviews.sf <- all_reviews %>%
  left_join(biz.sf, by= c("business_id" = "id"))
```


## Write geojson file
```{r write files}
st_write(reviews.sf, "park_reviews.geojson", driver = "geojson")
```
## Write boundary files
```{r write boundary files}
phl <- places(state = 42, year = 2022) %>%
  filter(NAME == "Philadelphia")

st_write(phl, "phl_bound.geojson", driver = "geojson")
```